config/routes.rb
Rails.application.routes.draw do
  resources :purchases
  resources :items
  resources :customers
  resources :merchants
  get '/auth/github/callback', to: 'sessions#create'
  get '/logout', to: 'sessions#destroy'
  get '/login', to: 'sessions#new'

  root to: 'welcome#show'

  resource :import, only: ['new', 'create']
end

app/models/customer.rb
class Customer < ActiveRecord::Base
  has_many :purchases

  def to_s
    name
  end
end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :merchant
  has_many :purchases

  def to_s
    "#{description}"
  end
end

app/models/merchant.rb
class Merchant < ActiveRecord::Base
  has_many :items
  has_many :purchases

  def to_s
    "#{name}, #{address}"
  end
end

app/models/purchase.rb
class Purchase < ActiveRecord::Base
  belongs_to :customer
  belongs_to :merchant
  belongs_to :item

  def total
    item.price * quantity
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  private

  def current_user= auth_hash
    session[:auth_hash] = auth_hash
  end

  def current_user
    if current_user = session[:auth_hash]
      Rails.logger.info 'Current User is set'
    else
      Rails.logger.info 'Current User is not set'
    end
    current_user
  end

  def authenticate_user!
    if !current_user
      redirect_to root_url, :alert => 'You need to sign in for access to this page.'
    end
  end

end

app/controllers/customers_controller.rb
class CustomersController < ApplicationController

  def index
    @customers = Customer.all
  end

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController

  before_filter :authenticate_user!

  def new
  end

  def create
    result = import_file
    if result[:success]
      redirect_to purchases_path, flash: result
    else
      redirect_to new_import_path, flash: result
    end
  rescue ActionController::ParameterMissing
    redirect_to new_import_path, flash: { error: 'Please select a file' }
  end

  private

  def import_file
    FileImporter.new(import_params[:file].tempfile.path).import!
  end

  def import_params
    params.require(:import).permit(:file)
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

  def index
    @items = Item.includes(:merchant).all
  end

end

app/controllers/merchants_controller.rb
class MerchantsController < ApplicationController

  def index
    @merchants = Merchant.all
  end

end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController

  def index
    @purchases = Purchase.includes(:merchant, :customer, :item).all
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
    if current_user
      redirect_to new_uplaod_path
    else
      redirect_to '/auth/github'
    end
  end

  def create
    self.current_user = auth_hash
    redirect_to root_path
  end

  def destroy
    session.destroy
    redirect_to root_path
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/customers_helper.rb
module CustomersHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/merchants_helper.rb
module MerchantsHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/views/customers/index.html.haml
%h1 Listing customers

%table
  %thead
    %tr
      %th Name

  %tbody
    - @customers.each do |customer|
      %tr
        %td= customer.name

app/views/imports/create.html.haml
%h1 Success!
= @contents[:file].original_filename

app/views/imports/new.html.haml
%h1 Import Transactions
%h4 Select a properly formatted csv file of transactions to continute

= form_for 'import', url: import_path, method: 'post' do |f|
  %p= f.file_field(:file)
  = f.submit('Import Data')

app/views/items/index.html.haml
%h1 Listing items

%table
  %thead
    %tr
      %th Description
      %th Price
      %th Merchant

  %tbody
    - @items.each do |item|
      %tr
        %td= item.description
        %td= item.price
        %td= item.merchant

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Deal-A-Day
    = stylesheet_link_tag 'application', media: 'all'
    = csrf_meta_tags
  %body
    = render 'shared/navigation'
    = render 'shared/flash'
    = yield

app/views/merchants/index.html.haml
%h1 Listing merchants

%table
  %thead
    %tr
      %th Name
      %th Address

  %tbody
    - @merchants.each do |merchant|
      %tr
        %td= merchant.name
        %td= merchant.address

app/views/purchases/index.html.haml
%h1 Listing purchases

%table
  %thead
    %tr
      %th Customer
      %th Merchant
      %th Item
      %th Quantity
      %th Total

  %tbody
    - @purchases.each do |purchase|
      %tr
        %td= purchase.customer
        %td= purchase.merchant
        %td= purchase.item
        %td= purchase.quantity
        %td= purchase.total

app/views/shared/_flash.html.haml
- flash.each do |name, msg|
  %p
    %em= "#{name}: #{msg}"

app/views/shared/_navigation.html.haml
- if current_user
  = link_to 'Sign out', logout_path
- else
  = link_to 'Sign in', login_path
| #{link_to 'Home', root_path}
- if current_user
  | #{link_to 'Import', new_import_path}
| #{link_to 'Customers',customers_path} | #{link_to 'Items', items_path}
| #{link_to 'Merchants', merchants_path} | #{link_to 'Purchases', purchases_path}

app/views/welcome/show.html.haml
%h1 Welcome to the Deal-a-Day data migration tool
- if current_user
  %p You can now import your data!
  = link_to 'Import your file', new_import_path
- else
  %p== Please #{ link_to 'sign in with your GitHub account', login_path }.